on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - run: yarn
      - name: 'Build site'
        run: yarn build
      - name: rsync
        if: ${{github.event_name=='push' && github.ref=='refs/heads/main'}}
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          DEPLOY_SRC: ./build/
          DEPLOY_DEST: sync/cs4110-2021fa
          DEPLOY_2_HOST: cslinux
          DEPLOY_2_DEST: /courses/cs4110/2021fa
        run: |
          echo "$DEPLOY_KEY" > pk
          echo "$DEPLOY_KNOWN_HOSTS" > kh
          chmod 600 pk
          rsync --compress --recursive --checksum --itemize-changes --delete \
            -e "ssh -p \"$DEPLOY_PORT\" -i pk -o 'UserKnownHostsFile kh'" \
            $DEPLOY_SRC $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DEST
          ssh -p $DEPLOY_PORT -i pk -o 'UserKnownHostsFile kh' \
            $DEPLOY_USER@$DEPLOY_HOST \
            rsync --compress --recursive --checksum --itemize-changes \
            --delete -e ssh --chmod=ugo=rwX \
            $DEPLOY_DEST/ $DEPLOY_2_HOST:$DEPLOY_2_DEST
